import type { CommandItem } from "@/lib/command/command.types";

/** Comandos estáticos do sistema — sem engines de jogo. */
export function getStaticCommands(): CommandItem[] {
  return [
    {
      id: "nav-terminal",
      title: "Abrir terminal",
      subtitle: "Central ao vivo",
      keywords: ["terminal", "live", "ao vivo", "central"],
      group: "Navegação",
      kind: "navigation",
      action: { type: "navigate", href: "/terminal" },
    },
    {
      id: "nav-ops",
      title: "Abrir OPS Center",
      subtitle: "Central operacional viva",
      keywords: ["ops", "operacoes", "operations", "mesa"],
      group: "Navegação",
      kind: "navigation",
      action: { type: "navigate", href: "/ops" },
    },
    {
      id: "nav-network",
      title: "Abrir Signal Exchange",
      subtitle: "Rede operacional contextual",
      keywords: ["network", "rede", "sinais", "consenso"],
      group: "Navegação",
      kind: "navigation",
      action: { type: "navigate", href: "/network" },
    },
    {
      id: "nav-workspace",
      title: "Abrir workspace",
      subtitle: "Watchlist e favoritos",
      keywords: ["workspace", "mesa", "favoritos"],
      group: "Navegação",
      kind: "navigation",
      action: { type: "navigate", href: "/workspace" },
    },
    {
      id: "filter-gpi-high",
      title: "Mostrar GPI > 85",
      subtitle: "Filtrar terminal por GPI extremo",
      keywords: ["gpi", "85", "extremo", "indice"],
      group: "Filtros",
      kind: "filter",
      action: { type: "terminal-filter", filter: "high_pressure", search: "gpi" },
    },
    {
      id: "filter-critical",
      title: "Jogos críticos",
      subtitle: "Alta pressão e prioridade operacional",
      keywords: ["criticos", "critical", "pressao", "hot"],
      group: "Filtros",
      kind: "filter",
      action: { type: "terminal-filter", filter: "high_pressure" },
    },
    {
      id: "filter-consensus",
      title: "Consenso alto",
      subtitle: "Abrir rede com contexto coletivo",
      keywords: ["consenso", "consensus", "convergencia"],
      group: "Filtros",
      kind: "filter",
      action: { type: "navigate", href: "/network" },
    },
    {
      id: "filter-market-distortion",
      title: "Distorção de mercado",
      subtitle: "OPS · monitor de edges",
      keywords: ["mercado", "odds", "edge", "ev", "distorcao"],
      group: "Filtros",
      kind: "filter",
      action: { type: "navigate", href: "/ops" },
    },
    {
      id: "action-broadcast",
      title: "Modo broadcast",
      subtitle: "TV / fullscreen no OPS Center",
      keywords: ["broadcast", "tv", "fullscreen", "stream"],
      group: "Ações",
      kind: "action",
      action: { type: "ops", broadcast: true },
    },
    {
      id: "action-replay",
      title: "Replay operacional",
      subtitle: "OPS · faixa tática",
      keywords: ["replay", "tatico", "historico"],
      group: "Ações",
      kind: "action",
      action: { type: "navigate", href: "/ops" },
    },
    {
      id: "action-multiview-4",
      title: "Abrir multi-view (4 jogos)",
      subtitle: "OPS Center · mosaico",
      keywords: ["multiview", "mosaico", "4", "quad"],
      group: "Ações",
      kind: "action",
      action: { type: "ops", view: 4 },
    },
    {
      id: "preset-trader",
      title: "Preset · Modo trader",
      subtitle: "Terminal · execução e varredura",
      keywords: ["trader", "trading", "execute"],
      group: "Presets",
      kind: "preset",
      action: { type: "preset", preset: "trader" },
    },
    {
      id: "preset-radar",
      title: "Preset · Modo radar",
      subtitle: "OPS · radar contextual",
      keywords: ["radar", "contexto", "scan"],
      group: "Presets",
      kind: "preset",
      action: { type: "preset", preset: "radar" },
    },
    {
      id: "preset-tv",
      title: "Preset · Modo TV",
      subtitle: "OPS · broadcast fullscreen",
      keywords: ["tv", "televisao", "livestream"],
      group: "Presets",
      kind: "preset",
      action: { type: "preset", preset: "tv" },
    },
    {
      id: "preset-quant",
      title: "Preset · Modo quantitativo",
      subtitle: "Insights e precisão",
      keywords: ["quant", "quantitativo", "analytics", "backtest"],
      group: "Presets",
      kind: "preset",
      action: { type: "preset", preset: "quant" },
    },
  ];
}

export function getQuickActionCommands(): CommandItem[] {
  return [
    {
      id: "qa-favorites",
      title: "Ver favoritos no terminal",
      keywords: ["favoritos", "favorites"],
      group: "Ações rápidas",
      kind: "action",
      action: { type: "terminal-filter", filter: "favorites" },
    },
    {
      id: "qa-live",
      title: "Ver jogos ao vivo",
      keywords: ["live", "ao vivo"],
      group: "Ações rápidas",
      kind: "action",
      action: { type: "terminal-filter", filter: "live" },
    },
  ];
}
