import type { OpsCenterPayload } from "@/lib/ops/opsCenter.types";

export function seedOpsCenterSandbox(): OpsCenterPayload {
  const now = new Date().toISOString();
  return {
    hero: {
      monitoredMatches: 6,
      activeAlerts: 4,
      avgGpi: 74,
      collectivePressure: 71,
      consensusScore: 68,
    },
    matches: [
      {
        fixtureId: "demo-liv-mci",
        matchLabel: "Liverpool × Man City",
        league: "Premier League",
        homeTeam: "Liverpool",
        awayTeam: "Man City",
        homeScore: 1,
        awayScore: 1,
        minute: 71,
        isLive: true,
        pressureScore: 81,
        gpiScore: 79,
        consensusScore: 72,
        priorityScore: 88,
        evContext: 0.14,
        oddsLag: true,
        ignoredByMarket: false,
      },
      {
        fixtureId: "demo-bar-atm",
        matchLabel: "Barcelona × Atlético",
        league: "La Liga",
        homeTeam: "Barcelona",
        awayTeam: "Atlético",
        homeScore: 0,
        awayScore: 0,
        minute: 54,
        isLive: true,
        pressureScore: 72,
        gpiScore: 68,
        consensusScore: 58,
        priorityScore: 76,
        evContext: 0.09,
        oddsLag: false,
        ignoredByMarket: true,
      },
      {
        fixtureId: "demo-int-mil",
        matchLabel: "Inter × Milan",
        league: "Serie A",
        homeTeam: "Inter",
        awayTeam: "Milan",
        homeScore: 2,
        awayScore: 1,
        minute: 82,
        isLive: true,
        pressureScore: 77,
        gpiScore: 75,
        consensusScore: 65,
        priorityScore: 82,
        evContext: 0.11,
        oddsLag: true,
        ignoredByMarket: false,
      },
    ],
    timeline: [
      {
        id: "tl-1",
        at: new Date(Date.now() - 180_000).toISOString(),
        kind: "gpi",
        label: "67' — GPI subiu para 76 · Liverpool × Man City",
        fixtureId: "demo-liv-mci",
        severity: "high",
      },
      {
        id: "tl-2",
        at: new Date(Date.now() - 150_000).toISOString(),
        kind: "consensus",
        label: "69' — watchlist operacional atualizada",
        fixtureId: "demo-liv-mci",
        severity: "medium",
      },
      {
        id: "tl-3",
        at: new Date(Date.now() - 120_000).toISOString(),
        kind: "telegram",
        label: "Telegram · alerta contextual enfileirado",
        fixtureId: "demo-liv-mci",
        severity: "medium",
      },
      {
        id: "tl-4",
        at: new Date(Date.now() - 60_000).toISOString(),
        kind: "goal",
        label: "74' — Gol · validação contextual",
        fixtureId: "demo-liv-mci",
        severity: "high",
      },
    ],
    radar: [
      {
        fixtureId: "demo-liv-mci",
        matchLabel: "Liverpool × Man City",
        league: "Premier League",
        criticality: 92,
        pressureScore: 81,
        gpiScore: 79,
        observerCount: 6,
        collectivePressure: 78,
      },
      {
        fixtureId: "demo-int-mil",
        matchLabel: "Inter × Milan",
        league: "Serie A",
        criticality: 84,
        pressureScore: 77,
        gpiScore: 75,
        observerCount: 3,
        collectivePressure: 71,
      },
    ],
    distortions: [
      {
        fixtureId: "demo-liv-mci",
        matchLabel: "Liverpool × Man City",
        market: "over_2.5",
        edgePercent: 6.2,
        ev: 0.14,
        laggedOdds: true,
        ignored: false,
        classification: "VALUE",
      },
      {
        fixtureId: "demo-bar-atm",
        matchLabel: "Barcelona × Atlético",
        market: "btts",
        edgePercent: 4.1,
        ev: 0.06,
        laggedOdds: false,
        ignored: true,
        classification: "IGNORE",
      },
    ],
    hotLeagues: [
      { league: "Premier League", heat: 142 },
      { league: "Serie A", heat: 98 },
      { league: "La Liga", heat: 76 },
    ],
    tacticalReplay: [
      {
        fixtureId: "demo-liv-mci",
        matchLabel: "Liverpool × Man City",
        minute: 67,
        note: "Ciclo ofensivo sustentado — pressão territorial",
      },
      {
        fixtureId: "demo-liv-mci",
        matchLabel: "Liverpool × Man City",
        minute: 71,
        note: "Convergência GPI + consenso rede",
      },
    ],
    sandbox: true,
    updatedAt: now,
  };
}
